### ISSUE TITLE
As a user, I want to have my headphones/volume calibrated so that I can ensure that my hearing test results are accurate

### ISSUE THREAD

**Issue by ghost** [mashalm/JD1_frontend#5] opened 2017-01-18 03:26 UTC

**Comment by mashalm** [comment] 2017-01-18 14:48
- Story / Task Details:
  - Integrate web audio API module
  - Design for calibration of headphones. 

- Acceptance criteria: Have some way to ensure an appropriate hearing level/headphones check so that 1. user is assured the issue is not with their technology instead of their hearing, and 2. there is an appropriate baseline created for all tests for data collection purposes

- Done Criteria: the user testing is completed, code merged to master branch, and code is peer-reviewed

**Closed as completed** 2017-03-13 03:43 UTC
